### ISSUE TITLE
Add permission to access setting page

### ISSUE THREAD

**Issue by ghost** [PopcornPHP/oc-imagecompress-plugin#8]
Hello,

It would be great to add permissions to access plugin settings page. I generally setup image compression during website development, and don't want to give access to that settings to the final customer.

Best regards,

Alex

**Comment by ghost** [comment]
Hi, is the module still maintained ? Would like to know if I have to fork it in order to make some PR

Thank you

**Comment by OleksandrWebLab** [comment]
Hi. You can create PR and I will merge it.

Thank you

**Comment by ghost** [comment]
[PR is already here](https://github.com/VoroninWD/oc-image-compress-plugin/pull/9) ^^
